### ISSUE TITLE
Review geotechnical engineering resource

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#10]
@EmilSoleymani please review the [geotechnical engineering material](https://github.com/smiths/vdisp/tree/main/Resources) prepared by Dr. Stolle.  The following is related to the project:

- Pages 1 -14 provides introduction material and a summary on stresses
- Pages 16-18 is on consolidation
- Pages 69-72 is on settlements

I think you will find this easier to read than the settlement analysis book.

**Comment by EmilSoleymani** [comment]
While figuring out most of the FORTRAN code I have read through relevant pages of the geotechnical engineering resources many times.
