### ISSUE TITLE
Add a Citation File

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#108]
We should add a Citation File to our repo, using the GitHub instructions for the [CITATION.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file.  We may also need to create a doi using Zenodo.  As an example, we've done these things with the [Drasil repo](https://github.com/JacquesCarette/Drasil).

**Comment by EmilSoleymani** [comment]
Added Citation file on `update-citation` branch. I have marked incomplete fields with "?".

https://github.com/smiths/vdisp/compare/main...update-citation

**Comment by smiths** [comment]
The file was updated in 68afc87.  I'll create an issue to update the remaining information on the initial version of vdisp.
