### ISSUE TITLE
Adopt a Code of Conduct

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#110]
We should incorporate a [code of conduct](https://opensource.guide/code-of-conduct/) into our project.  Some potential codes of conduct are listed on the [open code of conduct page.](https://github.com/todogroup/opencodeofconduct).  I think we could adapt the [Contributor Covenant](https://www.contributor-covenant.org/) fairly easily.

**Comment by EmilSoleymani** [comment]
Adapted Contributor Covenant in 087a65284b477669ed2bccd9479376f333e4e680 by adding file [CODE_OF_CONDUCT.md](CODE_OF_CONDUCT.md). Files inspired by code of conduct files from the [Visual F#](https://github.com/dotnet/fsharp) and [Atom](https://github.com/atom/atom) projects.
