### ISSUE TITLE
Change displacement graphs to use displacement/H

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#116]
@dstolle pointed out that the displacement versus depth plot is deceiving if all elements are not the same size.  The graphs don't match intuition, since small elements likely have small displacements, even if there displacement per unit length is high.  @dstolle suggests we normalize the data by dividing by the element thickness.  That is, we should use DH/H , that is the strain, when we plot the displacement data.

**Comment by EmilSoleymani** [comment]
Normalized all displacement data in graphs in 707f01278e60b57c8acf1f71e9ff54c90ed08ca7
