### ISSUE TITLE
Units information in the input file

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#119]
@EmilSoleymani, I've noticed that you have a hidden `.units` file.  The contents are either Metric or Imperial.  I think this information should be stored with the input file.  It isn't really an independent decision.  A problem is either Metric or Imperial.

I noticed this file because after testing vdisp for a bit the file changed and version control complained.  It doesn't make sense for this file to be under version control.  Every user will have their own setting for this file.

**Comment by EmilSoleymani** [comment]
Removed from version control in eaaf3f5f0ae72bb22b67ee8d892bb65f90851dfa. Julia now first checks if this file exists. If not it generates the file and writes a default value of "Imperial".

User can specify units in EnterDataStage1, or in input file. This file is just there to remember the users last choice as a "default", hopefully preventing a user from having to switch the units option too many times if they manually enter values.

**Comment by smiths** [comment]
Sounds good.
