### ISSUE TITLE
Wiki on Getting Started with Julia

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#12]
Along the lines of #11, let's create a Wiki page on getting started with Julia.  Our goal is to have a project that can be actively maintained.  This means that we are preparing for future developers.  Given that we have adopted Julia, it would be good to have some information on Julia.  We shouldn't teach Julia.  The wiki page would be a list of recommended readings - urls that interested parties can consult.  This also has the advantage of being useful for me and Dr. Stolle.  :smile:

**Comment by smiths** [comment]
Great work @EmilSoleymani.  Does Julia have an API documentation feature like Python ('pydoc')?  Based on the Documenter in the GitHub Actions, I'm pretty sure it does.  :smile:  Can you add a pointer in the wiki to information on how documentation is embedded into Julia code?

**Comment by EmilSoleymani** [comment]
Yes indeed it does, I used it to generate the (currently empty) documentation under `vdisp/docs`. In that directory there is a markdown file in which we can write our documentation (referring to our documention from code) and run the `make.jl` Julia script which makes a new `build` directory that has HTML output of our documentation. The Julia website had instructed me to add the `build` directory to my `.gitignore`. I wasn't sure why but I'm sure they know what they're talking about.
<img width="192" alt="image" src="https://user-images.githubusercontent.com/97846411/166694125-96ddaf4a-556e-4afa-bc6a-eef6311ea099.png">

**Comment by EmilSoleymani** [comment]
To add to that, the Documenter.yml is building our Documentation into GitHub pages. If you check under Settings>Pages a link should be shown to our currently empty docs

**Comment by smiths** [comment]
This is great.  Exactly what we want.  `build` is in your `.gitignore` file because generated files shouldn't be put under version control.  They are constantly being updated, but the changes aren't meant for humans, only for the computer.

I don't see the empty page under Settings>Pages, but I think I need to tell enable it.  I'll do so once the documentation is in the main branch.

**Comment by EmilSoleymani** [comment]
Documentation section added.

**Comment by smiths** [comment]
Looks good!
