### ISSUE TITLE
Julia linter

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#15]
We should look to see if there is a linter for Julia like `flake8` for Python.  Linters can be a great help in writing standardized code that avoids common pitfalls.  If such a tool exists, we could work it into our CI script.

**Comment by EmilSoleymani** [comment]
I was originally trying to use the `Lint` package which was the first search result when I searched up Julia linters. The reason it caused the FormatCheck to fail was because this package has been deprecated and is no longer supported by the Julia Package manager. I am now researching how to use the `StaticLint` package which can be found [here](https://github.com/julia-vscode/StaticLint.jl). This package seems a lot harder to use than the previous one, but following along [the example](https://github.com/julia-vscode/StaticLint.jl/wiki/Example) they provide I hope I can get it to work.

**Comment by smiths** [comment]
I agree that `StaticLint` looks challenging to use.  I feel like we should hold off on this goal for now.  It seems like StaticLint is written to work with VSCode, so for now we can recommend that developers use StaticLint while developing their code.

**Comment by EmilSoleymani** [comment]
Adding Julia packages changes our `Project.toml` and `Manifest.toml` files. These files might need inspection from time to time, thus I recommend the following [VSCode extension](https://marketplace.visualstudio.com/items?itemName=be5invis.toml) that provides syntax highlighting for `.toml` files.

**Comment by smiths** [comment]
@EmilSoleymani, I see the [Project.toml](https://github.com/smiths/vdisp/blob/main/Project.toml) file, but where is the Manifest.toml file.

We should explain the purpose of the Project.toml file and the Manifest.toml file in our README file.  Can you add that?  (If  you can't do it right away, please create an issue, so that we don't forget.)

Is there a candidate spot to add the .toml file VSCode extension advice in our documentation?  Maybe with the set-up instructions in the Getting Started Wiki?

**Comment by EmilSoleymani** [comment]
I forgot that the `Manifest.toml` file is part of the `.gitignore` as per Julia documentation.

**Comment by smiths** [comment]
What is the purpose of the `Manifest.toml` file?  Since it is not under version control, I'm assuming it is a generated file.  What application generates it, and when?

**Comment by EmilSoleymani** [comment]
`Manifest.toml` is an absolute record containing information about all the direct and indirect dependencies of the project.
The `Manifest.toml`  contains a list of all dependencies and the data associated with them. This data can vary based on how your Julia environment adds/installs these dependencies. "The `Manifest.toml` file is generated and maintained by Pkg and, in general, this file should never be modified manually." - [Pkg documentation](https://pkgdocs.julialang.org/v1/toml-files/#Manifest.toml).
There is a very interesting [discussion](https://discourse.julialang.org/t/does-manifest-toml-belong-in-the-repository/12029) here that lists out pros and cons of including a `Mainfest.toml`, with one con being that it could cause problems with CI.

**Comment by smiths** [comment]
Thank you for the explanation @EmilSoleymani.  I agree with your decision to leave Manifest.toml outside of version control.

**Comment by smiths** [comment]
@EmilSoleymani did you find a linter, or find that there isn't one?  We should include an explanation when we close an issue.

**Comment by EmilSoleymani** [comment]
I never managed to find a Julia linter other than `StaticLint.jl` which doesn't seem to be made to be implemented with GitHub actions unlike the deprecated `Lint.jl`

**Comment by smiths** [comment]
Okay.  We'll close this issue, although it might be something to reopen in the future as the Julia tools improve.
