### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#16]
Related to #8, our build is failing for the documenter.  Any guesses on why?  I did have my secret in the wrong spot before, but I've fixed that.  It doesn't complain about the environment key anymore, but it is failing for a new reason.

https://github.com/smiths/vdisp/actions/runs/2270910534

@EmilSoleymani, if you don't have any explanation, I can ask Jason for some ideas.

**Comment by smiths** [comment]
The problem is only caused when I push to the repo:

https://github.com/smiths/vdisp/actions

Is there something that needs to be changed in the permissions?

**Comment by smiths** [comment]
The pushed by @EmilSoleymani and by github_pages are working.  It is the `smiths` ones that are failing.

**Comment by EmilSoleymani** [comment]
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/97846411/166746357-5550d36a-3eaa-4096-90b7-9b6f70b74dbb.png">
Documenter seems to be working fine on my pull requests, but failing on you pushs

**Comment by EmilSoleymani** [comment]
<img width="981" alt="image" src="https://user-images.githubusercontent.com/97846411/166747544-41081158-afb4-4edf-87fc-c6ab6289fe24.png">
Somehow, we are getting a 403 error response when trying to access the repo? That's what I understand from the error message.
<img width="981" alt="image" src="https://user-images.githubusercontent.com/97846411/166747657-64c0cbeb-02f1-418a-a2ca-4aafbc40827e.png">
It is related to this line of code where I link our repo

**Comment by EmilSoleymani** [comment]
I realized there was no rule in Documenter that triggered tasks on pull requests. I have opened a pull request with this added functionality I wonder if this works

**Comment by smiths** [comment]
This may have worked @EmilSoleymani.  My last merge for the last pull request didn't cause any problems.  I'll do a regular commit and see what happens.

**Comment by smiths** [comment]
I may have spoke too soon.  I hadn't actually merged the pull request, only approved it.

**Comment by smiths** [comment]
Unfortunately, I was wrong.  Everything pushed by me, either directly, or as part of a pull request merge, fails.  Something with permissions?

**Comment by EmilSoleymani** [comment]
https://github.com/JuliaDocs/Documenter.jl/issues/1177 might have some relevance to our issue I am reading through it now

**Comment by smiths** [comment]
When I look at the [GitHub Actions](https://github.com/smiths/vdisp/actions), I notice that the steps are different for github-pages, EmilSoleymani and for smiths.  Maybe there is a clue in there somewhere?

**Comment by smiths** [comment]
I'm wondering if the problem is related to the github pages for this project.  The page doesn't exist:

https://smiths.github.io/vdisp/

I'll look into that.

**Comment by smiths** [comment]
I'm not sure why the gh-pages branch wasn't created automatically.  I wonder if we can create it manually?

**Comment by EmilSoleymani** [comment]
As suggested in https://github.community/t/permission-denied-to-github-actions-bot-even-though-pat-has-permission/248028/4 I will be adding
```
with:
  token: ${{ secrets.GH_TOKEN }}
```
under the rule that uses `actions/checkout`.

**Comment by smiths** [comment]
I manually created a gh-pages branch.  I’ll wait to see if that breaks anything before I accept your pull request.

_________________________________

Spencer Smith, Ph.D., PEng
Associate Professor
Department of Computing and Software
McMaster University

Tel: (905) 525-9140 X27929
Room: ITB/167
Web: http://www.cas.mcmaster.ca/~smiths
_________________________________

**Comment by EmilSoleymani** [comment]
My first plan did not work. However, form the [same article] I found this relevant info:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/97846411/166804542-fe095498-861c-4c68-aa0f-812c6d4f9649.png">
<img width="981" alt="image" src="https://user-images.githubusercontent.com/97846411/166804569-7e096399-66f9-4e62-a564-7c35562fdfe7.png">

**Comment by smiths** [comment]
I'm cautiously optimistic that you found the problem.  The permissions were set incorrectly.  I updated them and reran an old build that failed and now it worked!

**Comment by EmilSoleymani** [comment]
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/97846411/166805933-c0530892-404f-4a92-8753-fbe3494f000f.png">
Looks like a success

**Comment by EmilSoleymani** [comment]
Following the topic of deleting old branches and closing old issues, should we being deleting old workflow runs?

**Comment by smiths** [comment]
The build is no longer failing, so we can close this issue.

With respect to deleting old workflows, I don't see any harm in doing so.  I don't know if it is that problematic if we leave them though, since the older ones will just scroll off the screen.  I don't think they use any memory and they won't cause any future confusion.

Let's say deleting old workflows is optional.
