### ISSUE TITLE
Remove unnecessary branch

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#17]
I think we should remove this branch from the github actions instructions:

https://github.com/smiths/vdisp/blob/c6ec9801456d8125c03baea0388a90762a008c3f/.github/workflows/Documenter.yml#L5

**Comment by EmilSoleymani** [comment]
Oh yes I forgot that I was trying to do that. I tried on the main branch but it did not let me push.
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/97846411/166744274-767d5a99-b2e5-41eb-a419-a4ef23abc068.png">
I will do this on a new branch

**Comment by smiths** [comment]
You are right that you cannot push to `main`.  We set it up like that to force pull requests for changes.  It is a bit of a nuisance, but I think it will pay off in the long run.

**Comment by EmilSoleymani** [comment]
I forgot one line in the new branch. I will have to add it back to Runtests

**Comment by smiths** [comment]
Okay.

**Comment by EmilSoleymani** [comment]
Runtests working correctly again.
