### ISSUE TITLE
Meeting Agenda: Monday, May 2, 9:30 am (ITB/167)

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#2]
1. Introductions
2. Overview of project
3. [Getting started memo](https://github.com/smiths/vdisp/blob/main/Contributing/GettingStartedInformation.txt)
4. [Job Hazard Analysis](https://github.com/smiths/vdisp/blob/main/Contributing/JHA/JobHazardAnalysis.pdf)
5. Check card access

**Comment by smiths** [comment]
As a follow-up to the meeting: @EmilSoleymani, were you able to get card access to your workspace?  Are you settling in okay?

**Comment by EmilSoleymani** [comment]
> As a follow-up to the meeting: @EmilSoleymani, were you able to get card access to your workspace? Are you settling in okay?

Yes, I visited JHE and got my access card and have been working in ITB 236 for the past half hour or so.

**Comment by smiths** [comment]
Great!  I will send you JHA form now, so we can close the agenda for our meeting.

**Comment by EmilSoleymani** [comment]
JHA form signed

**Comment by smiths** [comment]
Thank you Emil.  I’ve forwarded the signed form to Laurie LeBlanc.  I’ve also asked her about the required training.

Best wishes.

_________________________________

Spencer Smith, Ph.D., PEng
Associate Professor
Department of Computing and Software
McMaster University

Tel: (905) 525-9140 X27929
Room: ITB/167
Web: http://www.cas.mcmaster.ca/~smiths
_________________________________
