### ISSUE TITLE
Module Guide

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#28]
@EmilSoleymani as you finish going through the FORTRAN code we should start planning your implementation.  To discuss the design, I would like you to write a module guide.  To write your module guide you can look at these resources:

- [Module Decomposition Lecture](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/tree/master/Lectures/L17_ModuleDecomposition)
- [Module Guide lecture](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/tree/master/Lectures/L18_MG)

You can consider using my [template module guide](https://gitlab.cas.mcmaster.ca/smiths/cas741/-/tree/master/BlankProjectTemplate/docs/Design/MG).  You don't need to fill in all of the sections though.  Your goal, to begin with, is to identify your proposed modules and the secrets and services for each module.

To understand your design, we'll also need a preliminary Module Interface Specification (MIS).  I'll create another issue (#29) about that.

**Comment by EmilSoleymani** [comment]
Since I have not seen an MG before I felt quite overwhelmed at first by the documents. I decided to break it down into the more familiar problem of drawing out a rough UML Class diagram of how I imagine our program will work. The diagram along with my notes about why I did certain things, and some pseudocode of certain important procedures is available in this pdf:
[MG.pdf](https://github.com/smiths/vdisp/files/8663477/MG.pdf)
Using this as a guide (either of what to do or what **not** to do based on your feedback 😄 ), I will develop a MG as my next step

**Comment by smiths** [comment]
Great start with the UML diagram @EmilSoleymani.  Let's talk about it further after our meeting with Dr. Stolle tomorrow.  I like the direction you are going, but some of the aspects are unclear to me.

We may end up documenting the design using UML, but I would like to give a good go at the MIS (Parnas inspired) approach.  Maybe we'll use both.  Using UML diagrams to think about the design is great.  Drawing the boxes and arrows can help clarify the design.  Using design patterns is also a great idea.  The advantage of the MIS approach is that we can be more mathematical.  Tool support isn't great though.

It might help you to look at a sample [module guide](https://github.com/smiths/swhs/blob/master/docs/Design/MG/PCM_MG.pdf) and [module interface specification](https://github.com/smiths/swhs/blob/master/docs/Design/MIS/PCM_MIS.pdf) for a solar water heating problem.

It might also help to look at the [MIS Format](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/MISFormat/MISFormat.pdf) that I used for 2AA4/2ME3.

As I mentioned above, we might decide to go with UML, but I am more comfortable with the Parnas-inspired approach.  We can discuss further on Wednesday.

**Comment by EmilSoleymani** [comment]
What's left for the preliminary MG:
- [ ] List down modules in module guide in *Table 1: Module Hierarchy*
- [ ] Explain each modules **secrets** and **services** in *Section 7: Module Decomposition*
- [ ] List *anticipated changes* (i.e. built-in unit conversions) in *Section 4.1: Anticipated Changes*

**Comment by EmilSoleymani** [comment]
Issue closed by #36
