### ISSUE TITLE
Add link to Settlement Book

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#31]
The link you found to the [Settlement Analysis book](https://www.publications.usace.army.mil/Portals/76/Publications/EngineerManuals/EM_1110-1-1904.pdf) is a great find.  Please add a link to the book in our README file.  We'll eventually do a better job of organizing this information.  For now, it is enough to put related information in the same file.

**Comment by EmilSoleymani** [comment]
Added link to README.md
