### ISSUE TITLE
Input Parsing

### ISSUE THREAD

**Issue by EmilSoleymani** [smiths/vdisp#37]
I decided to begin with the coding as discussed. I wanted to first tackle the problem of parsing the input file `VDIN.DAT` using Julia. This has been quite easy so far, I am about halfway done.

**Comment by smiths** [comment]
Great!  This isn't really an issue though.  :-)  I'm definitely very glad to get information of this sort, but it is probably best to e-mail it, rather than create an issue.  (Issues are things that have a clear path to closure.)
