### ISSUE TITLE
Update UML Diagram

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#39]
As I mentioned in the MG pull request, I think you are on to something with the UML diagram.  I think we may still document the design in the MG document, but for discussing the design, the graphical nature of the UML diagram and design patterns are better than a LaTeX document.

I'd like you to update your UML diagram, if you can, to remove the heavy use of strings in the interfaces.  I understand why you did that, but strings are an opaque data structure.  We only have the string.  We lose what it means.

I believe the problem is that the different options (NOPT?) lead to different outputs.  What if we have an interface that has behaviours that are the union of all possibilities?  In some cases the implementation of the behaviour will be uninteresting, or maybe even an error to request.  The good thing is that every option would then have the same behaviours.

If you have read the Head First Design Patterns book, you see an example like this with the Duck example at the start.  For instance, the ducks all have a quack method.  However, the wooden decoy ducks implement quack as silence.  I have a feeling we could do something analogous.

If you haven't seen the Head First design patterns book, I think I might have an electronic copy somewhere that I could look for.

**Comment by EmilSoleymani** [comment]
By simple google search I found the book [here](https://longbiao.spatial-crowdsensing.com/courses/scad/files/head-first-design-patterns-compressed.pdf). I am reading through the Duck example right now.

**Comment by smiths** [comment]
Great!  The book is a little silly, but I think it does a good job of teaching design patterns.

**Comment by EmilSoleymani** [comment]
The duck example was perfect for this situation and I have developed a rudimentary UML that seems to be a much better design. I will share as soon as I add some finishing touches.

**Comment by smiths** [comment]
Great!

**Comment by EmilSoleymani** [comment]
Here is the UML diagram of everything concerning the OutputData:
[New UML.pdf](https://github.com/smiths/vdisp/files/8688277/New.UML.pdf)
Following the duck example, I made various interfaces that deal with behaviours that often change, like ModelOutputBehaviour, FoundationOutputBehaviour and most importantly, CalculationBehaviour. The OutputData class will have an instance of each of these interfaces and the concrete implementation of the interface can be swapped at runtime as we please. OutputData also has some sections that are always written to output file, and their implementations are simply coded in the OutputData class. To provide more flexibility than just the *getOutput():String*  function from the previous UML iteration, each section(whether it is a changing or constant behaviour) now has 3 functions: one that writes the section to the file, one that returns all relevant values from the section, and the same getOutput function. The getValues() function will save us from having to parse sections again if we want their respective values. Finally, one of the most important additions is the final `writeOutput` function. It is very likely the user might want their own order of outputs, even omitting some data they don't need. We can take advantage of Julia's functional programming capabilities and pass in functions to the writeOutput method. This method will write the section to the output file in the order they are given. My current thought is it can be passed in as an array of functions, and by looping through each function in order and executing them we will achieve the desired output. If the user decides to omit a certain section, the code will not add that section's output function to the array that gets passed into `writeOutput`.

**Comment by EmilSoleymani** [comment]
I guess the best way to test the designs validity is to jump into coding it. To do so I first researched inheritance in Julia since it quite unorthodox (at least with respect to Java, Python, ...). [This video](https://youtu.be/nkSuEkmsB28) was the perfect resource. I came up with the code for `ModelOutputBehaviour`, and after a few mistakes I finally wrapped my head around what's going on and got everything to work:
``` Julia
@enum Model ConsolidationSwell LeonardFrost Schmertmann CollapsibleSoil SchmertmannElastic 

abstract type ModelOutputBehaviour end 
function writeOutput(modelOutBehaviour::ModelOutputBehaviour, path::String) 
    println("Writing \"$(getModelOutput(modelOutBehaviour))\" to file at $(path)")
end
function getModelOutput(modelOutBehaviour::ModelOutputBehaviour)
    return getOutput(modelOutBehaviour)
end
function getModelValue(modelOutBehaviour::ModelOutputBehaviour)
    return getValue(modelOutBehaviour)
end

struct ConsolidationSwellBehaviour <: ModelOutputBehaviour
    model::Model
    ConsolidationSwellBehaviour() = new(ConsolidationSwell)
end
getOutput(behaviour::ConsolidationSwellBehaviour) = "Model: " * string(behaviour.model)
getValue(behaviour::ConsolidationSwellBehaviour) = behaviour.model

struct LeonardFrostBehaviour <: ModelOutputBehaviour
    model::Model
    LeonardFrostBehaviour() = new(LeonardFrost)
end
getOutput(behaviour::LeonardFrostBehaviour) = "Model: " * string(behaviour.model)
getValue(behaviour::LeonardFrostBehaviour) = behaviour.model

A = ConsolidationSwellBehaviour()
B = LeonardFrostBehaviour()
writeOutput(A, "src/input.dat")
println(getModelOutput(B))
println(getModelValue(A))
```
Console Output:
``` console
Writing "Model: ConsolidationSwell" to file at src/input.dat
Model: LeonardFrost
ConsolidationSwell
```

**Comment by smiths** [comment]
I like the new design, as represented in the new UML diagram.  As you suggested, the best way to "test" the design is to start implementing it.  (Another way to "test" it is to start documenting it more carefully, using the MIS syntax we discussed a little previously.  We'll hold off on that for a bit though, since writing code has the benefit of a compiler.)  :smile:

I'll have to watch the suggested video, since I agree with you that inheritance looks a little strange in Julia.  :smile:

If you haven't done so already, can you add your inheritance video to the list of Julia resources on the wiki?

Since the new UML has been created, I think we can safely close this issue.
