### ISSUE TITLE
Setup VSCode for LaTeX

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#4]
Extensions: LaTeX Workshop
LTeX - enable picky rules when you are confident in a document
consider increasing "Sentence Cache Size"?

**Comment by EmilSoleymani** [comment]
Installed VSCode extensions for LaTeX document editing. Viewed some of my old `.tex` source files from my *2FA3 Discrete Mathematics II* course to examine syntax highlighting / explore some features of the new extension. 
> Enabled picky rules, increased cache size to 4000 incase we deal with some medium size documents during project

**Comment by smiths** [comment]
Great!
