### ISSUE TITLE
Current UML Diagram to MG Folder

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#50]
So that we can refer to the current view of the UML design document, please put it in the MG folder.  A picture of your hand-drawn design is fine for now, but at some point we should update to an electronic drawing, like that which can be generated via [draw.io](https://app.diagrams.net/).

**Comment by EmilSoleymani** [comment]
Addressed in commit 1b19d35cca4f179f2e8dcb46805e4e8823b2fea0 .

**Comment by smiths** [comment]
The design document (UML diagram) doesn't actually show up the [main branch docs/Design folder](https://github.com/smiths/vdisp/tree/main/docs/Design).  @EmilSoleymani can you please look into this?

**Comment by EmilSoleymani** [comment]
As mentioned in #122, a new issue was opened to resolve this: #132.
