### ISSUE TITLE
Documentation not updating?

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#70]
@EmilSoleymani, the CI system doesn't seem to be updating the [documentation](https://smiths.github.io/vdisp/dev/).  Do we need to do something to get it updated?

**Comment by EmilSoleymani** [comment]
The documentation is build based off the markdown file at `docs/index.md`. I have updated it in the latest PR, #71, in hopes that these changes are reflected on the documentation site upon merging branches. From my understanding, we design whole site with markdown.

**Comment by EmilSoleymani** [comment]
Note: the documentation of the readInputFile is just a temporary docstring to see if documentation does indeed show up on the deployed site upon merging of the `update-documenter` branch. This function may not even be in the final product.

**Comment by EmilSoleymani** [comment]
The documentation has updated as expected upon the merging of the `update-documenter` branch to `main`. Issue closed. We might consider opening another issue in which we document all existing functions in modules like InputParser, OutputFormat, CalculationBehaviour, ... .

**Comment by smiths** [comment]
Great!  Yes, we want to document the modules that have been implemented, but we can wait until we are confident that the design is stable.
