### ISSUE TITLE
Traceability between testing of modules and test cases

### ISSUE THREAD

**Issue by smiths** [smiths/vdisp#77]
The CI approach of testing as we go along is working well.  However, over time we are going to lose track of the traceability between test cases and the modules.  There are test cases from 5 different test files, but the test file names don't provide any clue as to what they are testing.  The output while running the tests is also uninformative.

Is there a way to test where the traceability to the modules is more obvious?  For instance, can we have separate testing files, with each file containing the unit tests for a corresponding module?

I don't know what the Julia way of doing this is, but as the project grows we are going to want to be able to maintain the test cases.  In the Verification and Validation plan we can make tables to show what test files and which test cases are testing which modules, but it would also help if the code was self documenting.

**Comment by EmilSoleymani** [comment]
The following commits have addressed this issue (currently on the `update-meeting` branch):

* 7f5c24eb01b30bc4bdedde4ab790d29d81a8ebb9
* b31022e94e6b7aa7c2ba24b5d0a6669380a48776
* d6bf31463da2d964a1029ea65b1b2e8c244e9245

Any new tests will continue this pattern of being separated by module.

**Comment by smiths** [comment]
Looks good @EmilSoleymani.
