### ISSUE TITLE
QML.jl problem

### ISSUE THREAD

**Issue by EmilSoleymani** [smiths/vdisp#85]
When I try to pass Julia functions to QML, a very important part of the process, I get an error that says "Could not find module QML when looking up function get_julia_call". This was not present in my [Julia Thermostat](https://github.com/EmilSoleymani/JuliaThermostat) example. A quick google search lead me to [this ***open*** issue](https://github.com/barche/QML.jl/issues/95) which explains the problem. It seems to be related to module QML being present in the same directory. Since our `vdisp.jl` is in the `vdisp/src/` folder, and our `Project.toml` is in `vdisp/`, the `QML.jl` module is not being found when I call the `@qmlfunction` macro.

**Comment by smiths** [comment]
I hope the fix is as straightforward as changing the location of the `Project.toml` file.

**Comment by EmilSoleymani** [comment]
Although this issue wasn't solved by moving around files, I did find a workaround for what I initially wanted to do in commit 4e07de4603156a0c1705e685042175b645811b1a. I hope this doesn't become a problem down the road.

**Comment by EmilSoleymani** [comment]
I haven't tried reverting the Julia versions yet. I could give it a try, however, I did think of a permanent workaround. Instead of having to call a `Julia` function directly from `QML` files, we can have `QML` forward a "signal" to `Julia` to call on the function. 

For example, we want to call the function `f`. In `vdisp.jl` we create `callF`. Using the `Observable.jl` library, we can set `callF` to `Observable(false)`. This will initialize `callF` to false, and allow us to get a "signal" any time `callF` is changed thanks to the `Observables.jl` library. Once we recieve the signal that `callF` is changed, we call `f()` in our `Julia` code (and set `callF` back to false). If we need arguments we can also have a variable to store those.

**Comment by smiths** [comment]
@EmilSoleymani I like that you found a potential work around.  As long as it is documented, I think the observer design pattern could feel fairly natural here.  It is hard to tell without seeing the code though.  Do you think the observer pattern will be easy to maintain, or will it confuse people that work with the code in the future?
