### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by EmilSoleymani** [smiths/vdisp#98]
Allow for use of different units

- [x] Create variable and enum in Julia to keep track of current units
- [x] Add unit labels beside each input box (add space between number and unit)
- [x] Add option to switch units in settings
- [x] Consider units in calculations
- [x] Confirm units used for each measurement

**Comment by smiths** [comment]
Sounds good @EmilSoleymani.  For the unit labels, you could also include them within the text to the left of the input box.  Whatever looks best and is easiest to implement.  :smile:

**Comment by EmilSoleymani** [comment]
@dstolle @smiths Just wanted to confirm the following units:

|      Measure     | Metric | Imperial |
|:----------------:|:------:|----------|
|    Dimensions    |    m   |    ft    |
|     Pressure     |   Pa   |    tsf   |
| Elastic Modulus  |   MPa  |    tsf   |
| Cone Penetration |   MPa  |    tsf   |

and that the following are unitless:
- specific gravity
- void ratio

**Comment by smiths** [comment]
The units look correct to me @EmilSoleymani.  However, for metric, I like everything to be in SI, so I would also do the Elastic Modulus and Cone Penetration on Pa.  I find I have to think less if everything is always in SI.  Having said that, if @dstolle says that it is common to express the material properties in MPa, that is fine with me.

**Comment by smiths** [comment]
I like the addition of units in the first Enter Data screen.  However, it would be nice to have a space between the number and the units.

**Comment by EmilSoleymani** [comment]
Closed in a4c99da2c2c430e74dc50066e219d091f39893ce
